name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make build folder
      run: cmake -B build
    - name: generate build
      run: cmake --build build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
